### ISSUE TITLE
Compatibility and/or Config Request

### ISSUE THREAD

**Issue by Tiago-o-Oliveira** [kuba6000/Mobs-Info#1]
### Draconic Evolution
- Support for mob souls (0,1% for hostile mobs and 0,125% for passive) 

- Support for Reaper Enchant which increases soul drop chances 

     <details><summary>Chance</summary>
     <p>
      
     |Level | None | I | II | III | IV | V|
     |-- | -- | -- | -- | -- | -- | --|
     |Any Sword | N/A | 0.1% | 0.2% | 0.3% | 0.4% | 0.5%|
     |Sword of the Wyvern and Bow of the Wyvern | 0.1% | 0.2% | 0.3% | 0.4% | 0.5% | 0.6%|
     |Draconic Sword and Draconic Bow | 0.2% | 0.3% | 0.4% | 0.5% | 0.6% | 0.7%|
     |Draconic Staff of Power | 0.3% | 0.4% | 0.5% | 0.6% | 0.7% | 0.8%|
     </p>
     </details> 
     <details><summary>For Animals</summary>
     <p>
     
     |Level | None | I | II | III | IV | V
     |--- | --- | --- | --- | --- | --- | ---
     |Any Sword | N/A | 0.125% | 0.25% | 0.376% | 0.5% | 0.625%
     |Sword of the Wyvern and Bow of the Wyvern | 0.125% | 0.25% | 0.376% | 0.5% | 0.625% | 0.75%
     |Draconic Sword and Draconic Bow | 0.25% | 0.376% | 0.5% | 0.625% | 0.75% | 0.877%
     |Draconic Staff of Power | 0.376% | 0.5% | 0.625% | 0.75% | 0.877% | 1%

     </p>
     </details> 

- Support for Dragon Heart drop and draconium drop from dragon

### Tinkers Construct
- Support for yellow and red hearts drop: Red hearts have a 0,5% chance to drop on any mob kill, yellow hearts have a 100% chance to drop on any boss kill

WIP

**Comment by kuba6000** [comment]
@Tiago-o-Oliveira 

https://github.com/kuba6000/Mobs-Info/releases/tag/0.0.2

https://modrinth.com/mod/mobsinfo/version/0.0.2

**Comment by Tiago-o-Oliveira** [comment]
Liked it really much, more suggestions like this are welcome ?

**Comment by kuba6000** [comment]
> Liked it really much, more suggestions like this are welcome ?

For sure
