### ISSUE TITLE
Crash with CT

### ISSUE THREAD

**Issue by KibaTheBarbarian** [kuba6000/Mobs-Info#13]
your mod crash with https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/2838720 it happens when going into the world https://pastebin.com/8G2JDCns  if need more info I can help my mod pack have like 300 mobs with diff drops so your mod rocks

**Comment by kuba6000** [comment]
@KibaTheBarbarian 
The crash report doesn't help very much.
Can you provide the fml-client-latest.log
Also does any of your crafttweaker scripts modify mob drops?
If so maybe you could also provide them.
And does this happen on single player or when starting a server or when you join a server?
