### ISSUE TITLE
Crash on startup on server on large modpack

### ISSUE THREAD

**Issue by quentin452** [kuba6000/Mobs-Info#45]
For now idk whats the cause
[fml-server-latest.log](https://github.com/kuba6000/Mobs-Info/files/12369256/fml-server-latest.log)

for now i don't have tiime to debug this

**Comment by kuba6000** [comment]
Please try this build https://github.com/kuba6000/Mobs-Info/releases/tag/0.1.2-pre

**Comment by quentin452** [comment]
seem to be fixed
