### ISSUE TITLE
Why did you change datas of players, And why didn't you test it?

### ISSUE THREAD

**Issue by qff233** [kuba6000/Mobs-Info#51]
When I kill other player on server, it will made me didn't join the server and no the grave were generated for the other player.  And it made me data explode. I have to rollback. Why your code change other date of player? Why you don't test your mod after it join the mod pack? It is so bed. It caused me to lose a lot of progress! I'm also a programmer, I just think the problem is very stupid.

**Comment by kuba6000** [comment]
I fixed the crash a while ago in https://github.com/kuba6000/Mobs-Info/releases/tag/0.1.1 please update.
