### ISSUE TITLE
a feature if possible

### ISSUE THREAD

**Issue by KibaTheBarbarian** [kuba6000/Mobs-Info#69]
is there a way for you to see what biome the mobs spawn in or a person can make a list
![wereat](https://github.com/kuba6000/Mobs-Info/assets/20373705/e8b37090-e7d5-4dc8-9af5-03b1cede417b)

**Comment by KibaTheBarbarian** [comment]
and can see if works with the dragon quest mod

**Comment by KibaTheBarbarian** [comment]
okay I testing the [package version](https://github.com/kuba6000/Mobs-Info/actions/runs/7358985225) and some of them say Ocean or Nothing at All

**Comment by kuba6000** [comment]
> okay I testing the [package version](https://github.com/kuba6000/Mobs-Info/actions/runs/7358985225) and some of them say Ocean or Nothing at All with using the dragon quest mod the [stacktrace](https://pastebin.com/zLapWLsm) that pop up in the console

Fixed
![image](https://github.com/kuba6000/Mobs-Info/assets/53441451/a2dee0ce-2869-46cb-8567-fc8966c66e45)
