### ISSUE TITLE
I found another bug

### ISSUE THREAD

**Issue by KibaTheBarbarian** [kuba6000/Mobs-Info#72]
the mod has an issue with [Just Another Spawner](https://www.curseforge.com/minecraft/mc-mods/just-another-spawner) only one that shows I think is the Ender Dragon event sorry about the late report

**Comment by KibaTheBarbarian** [comment]
any update on this?

**Comment by kuba6000** [comment]
Fixed https://github.com/kuba6000/Mobs-Info/releases/tag/0.3.0
