### ISSUE TITLE
Supporting villager trades

### ISSUE THREAD

**Issue by GedeonGrays** [kuba6000/Mobs-Info#80]
Hello o/

I spent a lot of time looking for a mod that can show me what trades can be in which professions of villagers, but apparently, for version 1.7.10, such a mod simply does not exist.

Could you please add a display of the trades available to each villager's profession? Mod support (or the ability to prescribe existing trades yourself) would be ideal.

I realize my suggestion may not align with your mod's goals, but I have no idea who else to turn to. Anyway, thanks for your time.

**Comment by kuba6000** [comment]
I will look into that

**Comment by kuba6000** [comment]
https://github.com/kuba6000/Mobs-Info/releases/tag/0.3.0

**Comment by GedeonGrays** [comment]
> https://github.com/kuba6000/Mobs-Info/releases/tag/0.3.0

Works perfectly, thank you so much!
